### ISSUE TITLE
3D armour bits don't go away when undressing character after changing race

### ISSUE THREAD

**Issue by goran2711** [Sonaza/DressUp#10]
I don't know how else to describe it, so [here is a screenshot](https://imgur.com/9xkvFZX) to demonstrate what I'm talking about.

To reproduce:
1. Be wearing an item whose appearance has 3D bits (e.g. the sleeves on [this chestpiece](http://www.wowhead.com/item=152679/gambeson-of-sargeras-corruption))
2. Open dressup
3. Choose a race to preview (can be you own)
4. Undress all

**Comment by Sonaza** [comment]
This is known error and limitation due to limited control of dress up model frames. To fix this Blizzard needs to do it, unfortunately there's no way I can help it.

**Comment by goran2711** [comment]
Aaah, gotcha! Fingers crossed they get around to addressing it then. Thanks for clearing this up.
