### ISSUE TITLE
DressUp Window UI Scale

### ISSUE THREAD

**Issue by loff93** [Sonaza/DressUp#12]
## Expected Behavior
Normally I'm able to resize the addon. By mistake I enlarged the window so big (it kind of glitched) it's outside of my WoW. I'm no longer able to resize the window.

## Actual Behavior
The UI is too big and the scale corner is out of my screen. I can't save or reset neither cause the window is too big. I can move the Window horizontal only.
## Steps to Reproduce the Problem

  1. Open Inspector / Dressing Room.
  2.
  3.

**Comment by Sonaza** [comment]
Added window reset option in the settings button menu and a new slash command **/dressup resetsize** to reset window size to default.

Additionally there's a safeguard option that automatically resets the size in case it's obviously way too big (doesn't fit on screen).

Said updates are coming in the version 3.0.4 which should be available on Curse now.

**P.S.** Those reproduction steps are quite lackluster. I mean I get what you mean by the rest of the issue message but with those reproduction steps this error would never be reproduced. You're missing the step "0. Resize the fuck out of the window"

**P.P.S.** Have you tried not resizing it too large?
