### ISSUE TITLE
Patch 8.2.5 lua on login and usage

### ISSUE THREAD

**Issue by reaper666735** [Sonaza/DressUp#14]
## Actual Behavior

Lua error when logging in after patch 8.2.5

## Steps to Reproduce the Problem

  1. update to 8.2.5
  2.log in

these are a phew of the errors i have been getting with 8.2.5:

1x DressUp\core.lua:608: attempt to index global 'DressUpModelControlFrame' (a nil value)
DressUp\core.lua:608: in function `ToggleGizmo'
DressUp\core.lua:513: in function <DressUp\core.lua:485>
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1208: in function <FrameXML\UIParent.lua:1106>

**********************************************************************************************

1x Error: Original call failed after running hooks for:  ContainerFrameItemButton_OnModifiedClick 
 FrameXML\DressUpFrames.lua:204: attempt to index local 'frame' (a nil value)(tail call): ?
[string "*:OnClick"]:10: in function <[string "*:OnClick"]:1>

(tail call): ?
Stubby\Stubby-8.2.6376 (SwimmingSeadragon).lua:382: in function <Stubby\Stubby.lua:326>
(tail call): ?
[string "*:OnClick"]:10: in function <[string "*:OnClick"]:1>

***********************************************************************************************

1x FrameXML\DressUpFrames.lua:204: attempt to index local 'frame' (a nil value)
FrameXML\DressUpFrames.lua:204: in function `DressUpFrame_Show'
DressUp\core.lua:1279: in function `DressUpVisual'
...ceBlizzard_Collections\Blizzard_Wardrobe.lua:1956: in function <...ceBlizzard_Collections\Blizzard_Wardrobe.lua:1930>

Locals:
frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"

**Comment by Sonaza** [comment]
Seems Blizz has completely nuked the original dressup frame model in favor of some kind of new monstrosity and fixing this requires a lot more work. As such I don't have any time estimates for getting it fixed right now.

**Comment by reaper666735** [comment]
well we can understand the delay :), 

i guess all we hope is that you do your best ^^

**Comment by Sonaza** [comment]
Fixed in v3.2.0-retail.
