### ISSUE TITLE
Character Panel error.

### ISSUE THREAD

**Issue by SinisterBrain** [Sonaza/DressUp#5]
Hi, after the recent update to v2.1.6 it's causing DejaCharacterStats to break my character panel.  It causes the panel to not extend showing the stats.  It seems to work otherwise but throws errors for me.
When I disable DressUp, DejaCharacterStats works fine.  
When I disable all addons but DressUp it errors and breaks the character panel.

Here's the error:

`13x DressUp\core.lua:231: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: in function`GetItemInfo'
DressUp\core.lua:231: in function `UpdatePaperDollItemLevels'
DressUp\core.lua:1148: in function`?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>

[string "safecall Dispatcher[3]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function`Fire'
Bartender4\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil`

Thanks for your time.

**Comment by Sonaza** [comment]
Oops. It's a very minor bug that I for some reason completely missed even when I thought about it before :penguin: 

Fixed in update 2.1.7.
