### ISSUE TITLE
patch 7.3 issue

### ISSUE THREAD

**Issue by reaper666735** [Sonaza/DressUp#6]
8x [string "*:OnShow"]:2: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
[string "*:OnShow"]:2: in function <[string "*:OnShow"]:1>
(tail call): ?
[C]: in function `Show'
FrameXML\UIParent.lua:2441: in function `SetUIPanel'
FrameXML\UIParent.lua:2282: in function `ShowUIPanel'
FrameXML\UIParent.lua:2151: in function <FrameXML\UIParent.lua:2147>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2935: in function `ShowUIPanel'
FrameXML\DressUpFrames.lua:113: in function <FrameXML\DressUpFrames.lua:105>
[C]: in function `DressUpFrame_Show'
DressUp\core.lua:1118: in function <DressUp\core.lua:1103>
(tail call): ?
(tail call): ?
(tail call): ?
FrameXML\ContainerFrame.lua:1077: in function <FrameXML\ContainerFrame.lua:1076>
[C]: ?
[C]: in function `pcall'
Stubby\Stubby-7.4.5714 (TasmanianThylacine).lua:380: in function <Stubby\Stubby.lua:326>
(tail call): ?
[string "*:OnClick"]:10: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = "igCharacterInfoOpen"

**Comment by Sonaza** [comment]
Issue has been fixed for version 2.3.0.
