### ISSUE TITLE
Green Background for Allied Races

### ISSUE THREAD

**Issue by Nox7M** [Sonaza/DressUp#8]
When I preview (CTRL + LMB) an Item with one of the Allied Races, the background is just green - and i can't change it with CTRL+Scroll.
But when I select one of the Allied Races in the drop down Menu, the Background is normal and changeable.

**Comment by Sonaza** [comment]
Oops. The addon is missing the allied race background images. Need to look into adding them in.

**Comment by Nox7M** [comment]
Thank you.

**Comment by Sonaza** [comment]
Solved the problem for version 2.3.3. Addon should update on Curse soon.

**Comment by XargonDragon** [comment]
This issue has cropped up again with the newly added Kul Tirans and Zandalari, alongside the inability to preview the new races

**Comment by Sonaza** [comment]
I don't have a subscription anymore and altough it's free weekend right now I don't have the races unlocked either. I'll try implementing some blind fixes.

**Comment by Sonaza** [comment]
Not sure if it works
