### ISSUE TITLE
Is it Possible to remove the Cogweel and SendOutfit Button in Charscreen?

### ISSUE THREAD

**Issue by Rushgarroth** [Sonaza/DressUp#9]
Would be nice to be able to remove/hide the Icons because its right above my Pawn Button and kind of distracting. For me its enough to just have a changed preview Window with the buttons being displayed there anyway.

**Comment by Sonaza** [comment]
Sorry it's taken so long but I finally got around to doing this for the upcoming Battle for Azeroth update next week.

Will be added in the version 3.0.0.
